version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: s_bank_app_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sbankapp
      MYSQL_USER: sbankuser
      MYSQL_PASSWORD: sbankpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: s_bank_app_web
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:

